
import type { Metadata } from "next";
import localFont from "next/font/local";
import {barlow, satisfy, arvo, inter,  robotoMono, playfair, acumin, pinksunset} from '@/lib/fonts'

import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { CartProvider } from "@/store/provider";
import { AuthProvider } from "@/store/authProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${satisfy.variable} ${arvo.variable} ${inter.variable} ${robotoMono.variable} ${barlow.variable} ${playfair.variable} ${geistMono.variable} ${acumin.variable} ${pinksunset.variable} antialiased `}
      >
        <AuthProvider>
          <CartProvider>
          <Header/>
          {children}
          {
            Footer()
          }
        </CartProvider>
        </AuthProvider>
      </body>      
    </html>
  );
}
